// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "SaveToRamAndOutput.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic SaveToRamAndOutput::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic SaveToRamAndOutput::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> SaveToRamAndOutput::ap_ST_fsm_state1 = "1";
const sc_lv<3> SaveToRamAndOutput::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> SaveToRamAndOutput::ap_ST_fsm_state4 = "100";
const sc_lv<32> SaveToRamAndOutput::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool SaveToRamAndOutput::ap_const_boolean_1 = true;
const sc_lv<32> SaveToRamAndOutput::ap_const_lv32_1 = "1";
const bool SaveToRamAndOutput::ap_const_boolean_0 = false;
const sc_lv<1> SaveToRamAndOutput::ap_const_lv1_0 = "0";
const sc_lv<1> SaveToRamAndOutput::ap_const_lv1_1 = "1";
const sc_lv<17> SaveToRamAndOutput::ap_const_lv17_0 = "00000000000000000";
const sc_lv<9> SaveToRamAndOutput::ap_const_lv9_0 = "000000000";
const sc_lv<8> SaveToRamAndOutput::ap_const_lv8_0 = "00000000";
const sc_lv<17> SaveToRamAndOutput::ap_const_lv17_19D07 = "11001110100000111";
const sc_lv<17> SaveToRamAndOutput::ap_const_lv17_1 = "1";
const sc_lv<9> SaveToRamAndOutput::ap_const_lv9_1 = "1";
const sc_lv<9> SaveToRamAndOutput::ap_const_lv9_173 = "101110011";
const sc_lv<18> SaveToRamAndOutput::ap_const_lv18_173 = "101110011";
const sc_lv<32> SaveToRamAndOutput::ap_const_lv32_2 = "10";

SaveToRamAndOutput::SaveToRamAndOutput(sc_module_name name) : sc_module(name), mVcdFile(0) {
    SaveToRamAndOutpubkb_U1 = new SaveToRamAndOutpubkb<1,1,9,10,9,18>("SaveToRamAndOutpubkb_U1");
    SaveToRamAndOutpubkb_U1->din0(grp_fu_161_p0);
    SaveToRamAndOutpubkb_U1->din1(grp_fu_161_p1);
    SaveToRamAndOutpubkb_U1->din2(grp_fu_161_p2);
    SaveToRamAndOutpubkb_U1->dout(grp_fu_161_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln28_fu_111_p2);
    sensitive << ( indvar_flatten_reg_72 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln28_fu_105_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_87_p4);
    sensitive << ( i_0_reg_83 );
    sensitive << ( icmp_ln28_reg_170 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( select_ln47_1_reg_184 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_161_p0);
    sensitive << ( icmp_ln28_reg_170 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_fu_161_p00 );

    SC_METHOD(thread_grp_fu_161_p00);
    sensitive << ( select_ln47_1_reg_184 );

    SC_METHOD(thread_grp_fu_161_p1);
    sensitive << ( icmp_ln28_reg_170 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_161_p2);
    sensitive << ( icmp_ln28_reg_170 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_fu_161_p20 );

    SC_METHOD(thread_grp_fu_161_p20);
    sensitive << ( select_ln47_reg_179 );

    SC_METHOD(thread_i_fu_117_p2);
    sensitive << ( ap_phi_mux_i_0_phi_fu_87_p4 );

    SC_METHOD(thread_icmp_ln28_fu_105_p2);
    sensitive << ( indvar_flatten_reg_72 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln29_fu_123_p2);
    sensitive << ( j_0_reg_94 );
    sensitive << ( icmp_ln28_fu_105_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_input_image_read);

    SC_METHOD(thread_j_fu_145_p2);
    sensitive << ( select_ln47_fu_129_p3 );

    SC_METHOD(thread_output_image_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln47_fu_157_p1 );

    SC_METHOD(thread_output_image_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_output_image_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_output_image_we0);
    sensitive << ( icmp_ln28_reg_170 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_select_ln47_1_fu_137_p3);
    sensitive << ( ap_phi_mux_i_0_phi_fu_87_p4 );
    sensitive << ( icmp_ln29_fu_123_p2 );
    sensitive << ( i_fu_117_p2 );

    SC_METHOD(thread_select_ln47_fu_129_p3);
    sensitive << ( j_0_reg_94 );
    sensitive << ( icmp_ln29_fu_123_p2 );

    SC_METHOD(thread_sext_ln47_fu_157_p1);
    sensitive << ( grp_fu_161_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln28_fu_105_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "SaveToRamAndOutput_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_image_dout, "(port)input_image_dout");
    sc_trace(mVcdFile, input_image_empty_n, "(port)input_image_empty_n");
    sc_trace(mVcdFile, input_image_read, "(port)input_image_read");
    sc_trace(mVcdFile, output_image_address0, "(port)output_image_address0");
    sc_trace(mVcdFile, output_image_ce0, "(port)output_image_ce0");
    sc_trace(mVcdFile, output_image_we0, "(port)output_image_we0");
    sc_trace(mVcdFile, output_image_d0, "(port)output_image_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_reg_72, "indvar_flatten_reg_72");
    sc_trace(mVcdFile, i_0_reg_83, "i_0_reg_83");
    sc_trace(mVcdFile, j_0_reg_94, "j_0_reg_94");
    sc_trace(mVcdFile, icmp_ln28_fu_105_p2, "icmp_ln28_fu_105_p2");
    sc_trace(mVcdFile, icmp_ln28_reg_170, "icmp_ln28_reg_170");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, add_ln28_fu_111_p2, "add_ln28_fu_111_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln47_fu_129_p3, "select_ln47_fu_129_p3");
    sc_trace(mVcdFile, select_ln47_reg_179, "select_ln47_reg_179");
    sc_trace(mVcdFile, select_ln47_1_fu_137_p3, "select_ln47_1_fu_137_p3");
    sc_trace(mVcdFile, select_ln47_1_reg_184, "select_ln47_1_reg_184");
    sc_trace(mVcdFile, j_fu_145_p2, "j_fu_145_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_87_p4, "ap_phi_mux_i_0_phi_fu_87_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, sext_ln47_fu_157_p1, "sext_ln47_fu_157_p1");
    sc_trace(mVcdFile, icmp_ln29_fu_123_p2, "icmp_ln29_fu_123_p2");
    sc_trace(mVcdFile, i_fu_117_p2, "i_fu_117_p2");
    sc_trace(mVcdFile, grp_fu_161_p3, "grp_fu_161_p3");
    sc_trace(mVcdFile, grp_fu_161_p0, "grp_fu_161_p0");
    sc_trace(mVcdFile, grp_fu_161_p1, "grp_fu_161_p1");
    sc_trace(mVcdFile, grp_fu_161_p2, "grp_fu_161_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, grp_fu_161_p00, "grp_fu_161_p00");
    sc_trace(mVcdFile, grp_fu_161_p20, "grp_fu_161_p20");
#endif

    }
    mHdltvinHandle.open("SaveToRamAndOutput.hdltvin.dat");
    mHdltvoutHandle.open("SaveToRamAndOutput.hdltvout.dat");
}

SaveToRamAndOutput::~SaveToRamAndOutput() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete SaveToRamAndOutpubkb_U1;
}

void SaveToRamAndOutput::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln28_reg_170.read(), ap_const_lv1_0))) {
        i_0_reg_83 = select_ln47_1_reg_184.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_83 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln28_fu_105_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_72 = add_ln28_fu_111_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_72 = ap_const_lv17_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln28_fu_105_p2.read(), ap_const_lv1_0))) {
        j_0_reg_94 = j_fu_145_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_0_reg_94 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln28_reg_170 = icmp_ln28_fu_105_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(icmp_ln28_fu_105_p2.read(), ap_const_lv1_0))) {
        select_ln47_1_reg_184 = select_ln47_1_fu_137_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln28_fu_105_p2.read(), ap_const_lv1_0))) {
        select_ln47_reg_179 = select_ln47_fu_129_p3.read();
    }
}

void SaveToRamAndOutput::thread_add_ln28_fu_111_p2() {
    add_ln28_fu_111_p2 = (!indvar_flatten_reg_72.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_biguint<17>(indvar_flatten_reg_72.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void SaveToRamAndOutput::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void SaveToRamAndOutput::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void SaveToRamAndOutput::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[2];
}

void SaveToRamAndOutput::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void SaveToRamAndOutput::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void SaveToRamAndOutput::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void SaveToRamAndOutput::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void SaveToRamAndOutput::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void SaveToRamAndOutput::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln28_fu_105_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void SaveToRamAndOutput::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void SaveToRamAndOutput::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void SaveToRamAndOutput::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void SaveToRamAndOutput::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void SaveToRamAndOutput::thread_ap_phi_mux_i_0_phi_fu_87_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln28_reg_170.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_0_phi_fu_87_p4 = select_ln47_1_reg_184.read();
    } else {
        ap_phi_mux_i_0_phi_fu_87_p4 = i_0_reg_83.read();
    }
}

void SaveToRamAndOutput::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void SaveToRamAndOutput::thread_grp_fu_161_p0() {
    grp_fu_161_p0 =  (sc_lv<9>) (grp_fu_161_p00.read());
}

void SaveToRamAndOutput::thread_grp_fu_161_p00() {
    grp_fu_161_p00 = esl_zext<18,9>(select_ln47_1_reg_184.read());
}

void SaveToRamAndOutput::thread_grp_fu_161_p1() {
    grp_fu_161_p1 =  (sc_lv<10>) (ap_const_lv18_173);
}

void SaveToRamAndOutput::thread_grp_fu_161_p2() {
    grp_fu_161_p2 =  (sc_lv<9>) (grp_fu_161_p20.read());
}

void SaveToRamAndOutput::thread_grp_fu_161_p20() {
    grp_fu_161_p20 = esl_zext<18,9>(select_ln47_reg_179.read());
}

void SaveToRamAndOutput::thread_i_fu_117_p2() {
    i_fu_117_p2 = (!ap_phi_mux_i_0_phi_fu_87_p4.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_phi_mux_i_0_phi_fu_87_p4.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void SaveToRamAndOutput::thread_icmp_ln28_fu_105_p2() {
    icmp_ln28_fu_105_p2 = (!indvar_flatten_reg_72.read().is_01() || !ap_const_lv17_19D07.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_72.read() == ap_const_lv17_19D07);
}

void SaveToRamAndOutput::thread_icmp_ln29_fu_123_p2() {
    icmp_ln29_fu_123_p2 = (!j_0_reg_94.read().is_01() || !ap_const_lv9_173.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_94.read() == ap_const_lv9_173);
}

void SaveToRamAndOutput::thread_input_image_read() {
    input_image_read = ap_const_logic_0;
}

void SaveToRamAndOutput::thread_j_fu_145_p2() {
    j_fu_145_p2 = (!select_ln47_fu_129_p3.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(select_ln47_fu_129_p3.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void SaveToRamAndOutput::thread_output_image_address0() {
    output_image_address0 =  (sc_lv<17>) (sext_ln47_fu_157_p1.read());
}

void SaveToRamAndOutput::thread_output_image_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        output_image_ce0 = ap_const_logic_1;
    } else {
        output_image_ce0 = ap_const_logic_0;
    }
}

void SaveToRamAndOutput::thread_output_image_d0() {
    output_image_d0 = ap_const_lv8_0;
}

void SaveToRamAndOutput::thread_output_image_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln28_reg_170.read(), ap_const_lv1_0))) {
        output_image_we0 = ap_const_logic_1;
    } else {
        output_image_we0 = ap_const_logic_0;
    }
}

void SaveToRamAndOutput::thread_select_ln47_1_fu_137_p3() {
    select_ln47_1_fu_137_p3 = (!icmp_ln29_fu_123_p2.read()[0].is_01())? sc_lv<9>(): ((icmp_ln29_fu_123_p2.read()[0].to_bool())? i_fu_117_p2.read(): ap_phi_mux_i_0_phi_fu_87_p4.read());
}

void SaveToRamAndOutput::thread_select_ln47_fu_129_p3() {
    select_ln47_fu_129_p3 = (!icmp_ln29_fu_123_p2.read()[0].is_01())? sc_lv<9>(): ((icmp_ln29_fu_123_p2.read()[0].to_bool())? ap_const_lv9_0: j_0_reg_94.read());
}

void SaveToRamAndOutput::thread_sext_ln47_fu_157_p1() {
    sext_ln47_fu_157_p1 = esl_sext<64,18>(grp_fu_161_p3.read());
}

void SaveToRamAndOutput::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln28_fu_105_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln28_fu_105_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void SaveToRamAndOutput::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_image_dout\" :  \"" << input_image_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_image_empty_n\" :  \"" << input_image_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_image_read\" :  \"" << input_image_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_image_address0\" :  \"" << output_image_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_image_ce0\" :  \"" << output_image_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_image_we0\" :  \"" << output_image_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_image_d0\" :  \"" << output_image_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

